// eslint-config-next 16 ships flat config arrays directly — no FlatCompat
// bridge, which throws a circular-structure error against ESLint 9.
import nextCoreWebVitals from "eslint-config-next/core-web-vitals";
import nextTypescript from "eslint-config-next/typescript";

const config = [
  {
    ignores: [
      ".next/**",
      ".open-next/**",
      ".wrangler/**",
      "design/**",
      "node_modules/**",
      "cloudflare-env.d.ts", // generated by `npm run cf-typegen`
    ],
  },
  ...nextCoreWebVitals,
  ...nextTypescript,
];

export default config;
